import React, { forwardRef, MouseEvent } from "react";
import { PetCharacter } from "../assets/pets/PetCharacter";
import type { PetGender } from "../../types";
import { useLanguage } from "../../contexts/LanguageContext";

interface ShareableListCardProps {
  names: string[];
  imagePreview: string | null;
  gender: PetGender;
  imageZoom?: number;
  imagePosition?: { x: number; y: number };
  onImageMouseDown?: (e: MouseEvent<HTMLDivElement>) => void;
  isDragging?: boolean;
}

export const ShareableListCard = forwardRef<
  HTMLDivElement,
  ShareableListCardProps
>(
  (
    {
      names,
      imagePreview,
      gender,
      imageZoom = 1,
      imagePosition = { x: 0, y: 0 },
      onImageMouseDown,
      isDragging = false,
    },
    ref,
  ) => {
    const { t } = useLanguage();

    let bgClass = "bg-[#d4c4e0]";
    if (gender === "Male") bgClass = "bg-[#aab2a1]";
    if (gender === "Female") bgClass = "bg-[#e889b5]";

    const imageStyle: React.CSSProperties = {
      transform: `scale(${imageZoom}) translate(${imagePosition.x}px, ${imagePosition.y}px)`,
      transition: isDragging ? "none" : "transform 0.1s linear",
      width: "100%",
      height: "100%",
      objectFit: "cover",
    };

    return (
      <div
        ref={ref}
        className={`${bgClass} p-12 flex flex-col items-center w-[460px] min-h-[750px] shadow-premium rounded-[4rem] overflow-hidden relative select-none border-[12px] border-white/20`}
      >
        <h2 className="text-bio-title text-6xl text-center mb-10 leading-none tracking-tighter">
          Help Me Choose!
        </h2>

        <div className="relative w-full aspect-square max-w-[340px] shadow-2xl rounded-[3rem] overflow-hidden bg-black/10 border-4 border-white/10 mb-10">
          <div
            className="w-full h-full flex items-center justify-center relative"
            onMouseDown={onImageMouseDown}
          >
            {imagePreview ? (
              <img
                src={imagePreview}
                alt="My Pet"
                style={imageStyle}
                draggable="false"
                className="pointer-events-none select-none"
              />
            ) : (
              <PetCharacter
                pet="cat"
                className="w-[200px] h-[200px] opacity-80"
              />
            )}
          </div>
        </div>

        <div className="w-full flex-grow">
          <div className="bg-white/90 backdrop-blur-md rounded-[3rem] p-10 shadow-xl flex flex-col items-center">
            <h3 className="text-2xl font-black text-[#AA336A] uppercase tracking-widest mb-6 font-heading">
              My Top Picks
            </h3>
            <ul className="space-y-4">
              {names.map((name, i) => (
                <li
                  key={i}
                  className="text-4xl font-black text-[#333] font-heading uppercase tracking-tighter"
                >
                  {name}
                </li>
              ))}
            </ul>
          </div>
        </div>

        <div className="mt-8 mb-2 text-[11px] font-black text-white/50 tracking-[0.4em] uppercase font-heading">
          GENERATED BY NAMEMYPET.ORG
        </div>
      </div>
    );
  },
);

ShareableListCard.displayName = "ShareableListCard";
